# Topic Format
#    Replace format
#      {server} : "Topic.ServerName" defined value.
#      {plugin} : The name of the plugin you requested to send. 
DateFormat: "yyyy/MM/dd HH:mm:ss.SSS"
Topic:
  UserLogin:
    Enable: true
    Format: "{server}/p/{plugin}/login"
    URL: ""
  UserLogout:
    Enable: true
    Format: "{server}/p/{plugin}/logout"
    URL: ""

Mqtt:
  Publish:
    QoS: 0
