# Topic Format
#    Replace format
#      {server} : "Topic.ServerName" defined value.
#      {plugin} : The name of the plugin you requested to send. 
DateFormat: "yyyy/MM/dd HH:mm:ss.SSS"
Topic:
  OnEnable:
    Enable: true
    Format: "{server}/p/{plugin}/onenable"
    URL: ""
  OnDisable:
    Enable: true
    Format: "{server}/p/{plugin}/ondisable"
    URL: ""
  UserLogin:
    Enable: true
    Format: "{server}/p/{plugin}/login"
    URL: ""
  UserLogout:
    Enable: true
    Format: "{server}/p/{plugin}/logout"
    URL: ""

Mqtt:
  Publish:
    QoS: 0

UUIDLogger:
  Enabled: false
  Database:
    type: "sqlite"
    name: "uuid.db"
    server: "localhost:port"
    user: "user"
    pass: "pass"
  ImportEnabled: false
  Import:
    type: "sqlite"
    name: "import.db"
    server: "localhost:port"
    user: "user"
    pass: "pass"

OnlinePlayerLogger:
  Enabled: false
  Database:
    type: "sqlite"
    name: "online.db"
    server: "localhost:port"
    user: "user"
    pass: "pass"
  